---
kind: pipeline
type: docker
name: default

trigger:
 branch:
   - main
 event:
   - push
   - pull_request


steps:
 - name: hello
   image: busybox
   commands:
     - echo hello world

 - name: build-public
   image: docker
   environment:
     USERNAME:
       from_secret: docker_username
     PASSWORD:
       from_secret: docker_password
     TOKEN:
       from_secret: drone_token
     SERVER:
       from_secret: drone_server
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   commands:
     - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
     - export DRONE_SERVER=$SERVER
     - export DRONE_TOKEN=$TOKEN
     - service docker start
     - cd public
     - docker build -t mypublic:latest .
     - docker tag mypublic:latest ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}
     - docker push ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}
     - docker image rm -f ravi0153/codebuffer:mypublic${DRONE_COMMIT:0:7}


 - name: build-server
   image: docker
   environment:
     USERNAME:
       from_secret: docker_username
     PASSWORD:
       from_secret: docker_password
     TOKEN:
       from_secret: drone_token
     SERVER:
       from_secret: drone_server
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
   commands:
     - echo "$PASSWORD" | docker login -u "$USERNAME" --password-stdin
     - export DRONE_SERVER=$SERVER
     - export DRONE_TOKEN=$TOKEN
     - service docker start
     - cd server
     - docker build -t myserver:latest .
     - docker tag myserver:latest ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}
     - docker push ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}
     - docker image rm -f ravi0153/codebuffer:myserver${DRONE_COMMIT:0:7}